unbanking/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('upvote.urls')),
]

upvote/urls.py
from django.conf.urls import url

from . import views

app_name = 'upvote'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^un/(?P<slug>[\w\-]+)$', views.DetailView.as_view(), name='detail'),
    url(r'^un/(?P<slug>[\w\-]+)/vote/$', views.vote, name='vote'),
    url(r'^ajax/vote/$', views.ajax_vote, name='ajax_vote'),
]

upvote/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import RegexValidator
from django.utils.text import slugify

from .utils import format_word

class Submission(models.Model):
    letters = RegexValidator(r'^[a-zA-Z\s]*$', 'Only letters and spaces are allowed.')

    name = models.CharField(max_length=50, validators=[letters])
    word = models.CharField(max_length=25, unique=True, validators=[letters])
    published_date = models.DateTimeField(default=timezone.now)
    disabled = models.BooleanField(default=False)
    slug = models.SlugField(editable=False)

    def __str__(self):
        return self.word

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.word)

        self.word = format_word(self.word)
        super(Submission, self).save(*args, **kwargs)

class Vote(models.Model):
    submission = models.ForeignKey(Submission, on_delete=models.CASCADE)
    submission_date = models.DateTimeField(default=timezone.now, editable=False)

    def __str__(self):
        return "Added on {date}".format(date=self.submission_date)

upvote/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Submission, Vote
from .utils import contains_profanity

class SubmissionForm(forms.ModelForm):
    class Meta:
        model = Submission
        fields = ['word', 'name']
        widgets = {
            'word': forms.TextInput(attrs={'placeholder': 'Enter your submission'}),
            'name': forms.TextInput(attrs={'placeholder': 'Enter your name'}),
        }

    def clean_word(self):
        word = self.cleaned_data['word']
        if contains_profanity(word):
            raise ValidationError("Let's keep it classy. Please suggest another word.")
        else:
            return word

    def clean_name(self):
        name = self.cleaned_data['name']
        if contains_profanity(name, False):
            raise ValidationError("Let's keep it classy. Please provide another name.")
        else:
            return name

class VoteForm(forms.ModelForm):
    class Meta:
        model = Vote
        fields = ['submission', ]

upvote/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View, DetailView
from django.db.models import Count
from django.contrib import messages
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Submission, Vote
from .forms import SubmissionForm
from .utils import format_word


def index(request):
    template_name = 'upvote/index.html'
    paginate_by = 10

    duplicate_message = "Great minds think alike! Your word has already been submitted, so please choose another word or help vote this one to the top."
    thanks_message = "Thank you for your submission! Vote for your word to help it get to the top!"

    submissions = Submission.objects \
        .annotate(votes=Count('vote')) \
        .order_by('-votes') \
        .filter(disabled=False)
    page = request.GET.get('page', 1)
    paginator = Paginator(submissions, paginate_by)
    try:
        top_submissions = paginator.page(page)
    except PageNotAnInteger:
        top_submissions = paginator.page(1)
    except EmptyPage:
        top_submissions = paginator.page(paginator.num_pages)

    if request.method == 'POST':
        form = SubmissionForm(request.POST)
        # Check whether the user has already submitted a word or voted
        submitted_word = format_word(form.data['word'])

        if Submission.objects.filter(word=submitted_word).exists():
            submission = Submission.objects.filter(word=submitted_word).get()
            messages.add_message(request, messages.INFO, duplicate_message)
            return HttpResponseRedirect(reverse('upvote:detail', args=(submission.slug,)))
        if form.is_valid():
            submission = form.save(commit=False)
            submission.save()
            messages.add_message(request, messages.SUCCESS, thanks_message)
            return HttpResponseRedirect(reverse('upvote:detail', args=(submission.slug,)))
    else:
        form = SubmissionForm()

    return render(request, template_name, {
        'form': form,
        'top_submissions': top_submissions,
        })

class DetailView(DetailView):
    model = Submission
    template_name = 'upvote/detail.html'

def vote(request, slug):
    submission = get_object_or_404(Submission, slug=slug)
    word = submission.word
    voted_list = request.session.get('voted', [])
    if word in voted_list:
        voted_message = "You've already voted for {word}, but you can always share to get more votes!".format(word=word.upper())
        messages.add_message(request, messages.WARNING, voted_message)
    else:
        vote = Vote(submission=submission)
        vote.save()
        voted_list.append(word)
        request.session['voted'] = voted_list
        messages.add_message(request, messages.SUCCESS, "Thank you for voting. Remember to share to help your word reach the top!")
    return redirect('upvote:index')

def ajax_vote(request):
    data = {}
    if request.method == 'POST':
        slug = request.POST.get('slug')
        data['slug'] = slug
        submission = get_object_or_404(Submission, slug=slug)
        word = submission.word
        voted_list = request.session.get('voted', [])
        if word in voted_list:
            voted_message = "You've already voted for {word}, but you can always share to get more votes!".format(word=word.upper())
            data['message'] = voted_message
        else:
            vote = Vote(submission=submission)
            vote.save()
            voted_list.append(word)
            request.session['voted'] = voted_list
            voted_message = "Thank you for voting. Remember to share to help your word reach the top!"
            data['message'] = voted_message
            data['success'] = True
    if not data['message']:
        data['message'] = "Something went wrong!"
    return JsonResponse(data)

upvote/templates/upvote/detail.html
{% extends 'upvote/layout/base.html' %}

{% block content %}
  <section class="bg-white">
    <div class="container">
      <div class="row p-3">
        <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 text-center">
          <h3>One more step! Don't leave your suggestion to fend for itself, share it online to get more votes and rise to be crowned a Canadian hero!</h3>
        </div>
        <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 py-3">
          {% include 'upvote/partials/word_display.html' %}
        </div>
      </div>
    </div>
  </section>
{% endblock %}

upvote/templates/upvote/index.html
{% extends 'upvote/layout/base.html' %}
{% load static %}

{% block content %}
  {% include 'upvote/partials/carousel.html' %}
  <section class="bg-purple">
    <div class="container">
      <div class="row py-4">
        <div class="col-12 col-sm-8 offset-sm-2">
          <div class=" mx-auto">
            <h1 id="carousel-text">Starting in 2018, credit unions in Canada won’t be allowed to use the term “banking” to describe the services they offer.</h1>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="bg-white">
    <div class="container">
      <div class="row py-4">
        <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
          <span class=" mx-auto">
            <h1 id="subtext" class="text-uppercase">Help us come up with a new term!</h1>
          </span>
          <form id="submission-form" method="post" action="{% url 'upvote:index' %}" class="form-group row my-4">
            {% csrf_token %}
              <div class="col-12 col-lg-8">
                {{ form }}
              </div>
              <div class="col-12 col-lg-4 pt-2">
                <button type="submit" id="search-btn" class="btn text-uppercase">Submit your replacement for "banking"
                </button>
              </div>
            </form>
            <!--<div class="row">
              <div class="col">
                <a href="#most-popular" class="filter-titles">MOST POPULAR</a>
              </div>
              <div class="col">
                <a href="#most-recent" class="filter-titles">MOST RECENT</a>
              </div>
              <div class="col">
                <a href="#random" class="filter-titles">RANDOM</a>
              </div>
            </div>-->
            {% if top_submissions %}
              <div class="row px-3">
                <div class="col-12 infinite-container">
                  {% for submission in top_submissions %}
                    {% include 'upvote/partials/word_display.html' %}
                  {% endfor %}
                </div>
              </div>
              <div class="row loading bg-purple text-center text-white" style="display: none;">
                <div class="col-12">
                  <h1>Loading...</h1>
                </div>
              </div>
              {% if top_submissions.has_next %}
                <div class="row">
                  <div class="col-12">
                    <div class=" mx-auto">
                      <a class="load-btn btn btn-lg infinite-more-link" href="?page={{ top_submissions.next_page_number }}">Load More</a>
                    </div>
                  </div>
                </div>
              {% endif %}
            {% else %}
              <div class="row">
                <div class="col-12">
                  <p>Be the first to add your word!</p>
                </div>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </section>
{% endblock %}

upvote/templates/upvote/layout/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Unbanking.ca</title>
    <!-- OpenGraph -->
    <meta property="og:title" content="Vote Now!" />
    <meta property="og:url" content="http://unbanking.ca/" />
    <meta property="og:image" content="{% static 'upvote/images/slide_1.jpg' %}" />
    <meta property="og:description" content="Starting in 2018, credit unions won’t be allowed to use the word ‘banking’ anymore. Help them choose a new word!" />
    <link rel="icon" type="image/png" href="{% static 'upvote/images/favicon.ico' %}" sizes="16x16" />
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'upvote/images/apple-touch-icon-144x144.png' %}" />
    <link rel="apple-touch-icon-precomposed" sizes="152x152" href="{% static 'upvote/images/apple-touch-icon-152x152.png' %}" />
    <link rel="icon" type="image/png" href="{% static 'upvote/images/favicon-32x32.png' %}" sizes="32x32" />
    <link rel="icon" type="image/png" href="{% static 'upvote/images/favicon-16x16.png' %}" sizes="16x16" />
    <meta name="application-name" content="Unbanking"/>
    <meta name="msapplication-TileColor" content="#4CAF76" />
    <meta name="msapplication-TileImage" content="{% static 'upvote/images/mstile-144x144.png' %}" />
    <!-- CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'upvote/css/main.css' %}" />
    <!-- JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/137a5a9211.js"></script>
    <script src="{% static 'upvote/js/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'upvote/js/infinite.min.js' %}"></script>
    <script src="{% static 'upvote/js/main.js' %}"></script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-102811259-1', 'auto');
      ga('send', 'pageview');
    </script>
  </head>
  <body>
    {% include 'upvote/partials/messages.html' %}
    {% include 'upvote/partials/navigation.html' %}
    {% block content %}
    {% endblock %}
    {% include 'upvote/partials/footer.html' %}
    <script>
      var infinite = new Waypoint.Infinite({
          element: $('.infinite-container')[0],
          onBeforePageLoad: function () {
              $('.loading').show();
          },
          onAfterPageLoad: function ($items) {
              $('.loading').hide();
          }
      });
    </script>
  </body>
</html>

upvote/templates/upvote/partials/carousel.html
{% load static %}

<header class="bg-purple">
  <div class="container">
    <div id="carousel" class="row">
      <div class="col-1 hidden-sm-down">
        <a class="carousel-controls carousel-control-prev" href="#unbankingCarousel" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
      </div>
      <div id="unbankingCarousel" class="carousel slide col-12 col-sm-8 mx-auto" data-ride="carousel">
        <div class="carousel-inner" role="listbox">
          <div class="carousel-item active">
            <div class="container-fluid">
              <img class=" img-fluid mx-auto carousel-sizing" src="{% static 'upvote/images/slide_1.jpg' %}" alt="First slide">
            </div>
          </div>
          <div class="carousel-item">
            <div class="container-fluid">
              <img class=" img-fluid mx-auto carousel-sizing" src="{% static 'upvote/images/slide_2.jpg' %}" alt="Second slide">
            </div>
          </div>
          <div class="carousel-item">
            <div class="container-fluid">
              <img class=" img-fluid mx-auto carousel-sizing" src="{% static 'upvote/images/slide_3.jpg' %}" alt="Third slide">
            </div>
          </div>
        </div>
      </div>
      <div class="col-1 hidden-sm-down">
        <a class="carousel-controls carousel-control-next" href="#unbankingCarousel" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
    </div>
  </div>
</header>

upvote/templates/upvote/partials/footer.html
<section class="bg-muted">
  <div class="container">
    <div class="row p-3">
      <div class="col-12 p-4 text-center">
        <h4>It’s estimated that having to change over from the term "banking" will cost Canadian credit unions more than <strong>$80 million</strong> for signage, printing and name changes. We think that's ridiculous.</h4>
      </div>
    </div>
</section>
<footer class="bg-teal">
  <div class="container">
    <div class="row pt-5 pb-5">
      <div class="col-12 text-white text-center">
        <h4>To learn more about this decision and how you can get it reversed, visit <a href="https://ccua.com/en" target="_blank">CCUA.com</a></h4>
      </div>
      <div class="col-12 pt-3 text-center text-white">
        <p><strong>Disclaimer:</strong> unbanking.ca is not affiliated with the Canadian Credit Union Association or the Office of the Superintendent of Financial Institutions (OSFI). We are simply advocates for Canadian credit unions and we believe that credit unions should be exempt from this legislation.</p>
      </div>
    </div>
  </div>
</footer>

upvote/templates/upvote/partials/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show p-4" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
      {{ message }}
    </div>
  {% endfor %}
{% endif %}
<noscript>
  <div class="alert alert-danger alert-dismissible fade show p-4" role="alert">
    Whoops! It looks like you have JavaScript disabled. Please enable it for the full experience.
  </div>
</noscript>
<div class="alert alert-danger alert-sticky fade p-4 text-center" role="alert">
  <span id="alert-message"></span>
</div>

upvote/templates/upvote/partials/navigation.html
{% load static %}

<nav class="bg-purple py-2">
  <div class="container">
    <div class="row align-items-center justify-content-center">
      <div class="col-12 text-center p-3">
        <a href="{% url 'upvote:index' %}">
          <img src="{% static 'upvote/images/logo.png' %}" class="mx-auto  img-fluid" />
        </a>
      </div>
      <div class="col-12 col-sm-4 sponsor-logo logo-right">
        <a href="https://cumark.ca" target="_blank">
          <img src="{% static 'upvote/images/cumark.png' %}" class="mx-auto img-fluid" />
        </a>
      </div>
      <div class="col-12 col-sm-1 p-4 text-white text-center">
        +
      </div>
      <div class="col-12 col-sm-4 sponsor-logo">
        <a href="https://www.luminusfinancial.com/" target="_blank">
          <img src="{% static 'upvote/images/luminus.png' %}" class="mx-auto img-fluid" />
        </a>
      </div>
    </div>
  </div>
</nav>

upvote/templates/upvote/partials/word_display.html
{% load static %}

<div id="{{ submission.slug }}" class="row bg-purple infinite-item align-items-center justify-content-between p-4 mb-2">
  <div class="col-12 col-sm-8">
    <a href="{% url 'upvote:detail' submission.slug %}">
      <h1 id="user-submission">{{ submission.word }}</h1>
    </a>
    <h5 id="user-name">{{ submission.name }}</h5>
  </div>
  <div class="col-6 col-sm-2 logo-base">
    <button class="vote-btn" onclick="vote('{{ submission.slug }}')">
      <i class="fa fa-heart" aria-hidden="true"></i>
    </button>
    <noscript>
      <form id="vote" action="{% url 'upvote:vote' submission.slug %}" method="post">
        {% csrf_token %}
        <button id="submitVote" type="submit" class="vote-btn">
          <i class="fa fa-heart" aria-hidden="true"></i>
        </button>
      </form>
    </noscript>
    <h3 id="vote-count" class="entry-subtext">{{ submission.vote_set.count }}</h3>
  </div>
  <div class="col-6 col-sm-2 logo-base dropdown">
    <div id="dLabel" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" class="share-btn text-center">
      <i class="fa fa-share-alt" aria-hidden="true"></i>
      <div class=" mx-auto">
        <h3 class="entry-subtext">SHARE</h3>
      </div>
    </div>
    <div class="dropdown-menu" aria-labelledby="dLabel">
        <a class="dropdown-item" href="https://twitter.com/share?url=http%3A%2F%2Funbanking.ca{% url 'upvote:detail' submission.slug %}&hashtags=thisisridiculous,unbanking&related=wearecumark&text={{ submission.word|upper|urlencode }} would make a great new term for 'banking'. Vote to get it to the top!"
        >Twitter</a>
        <a class="dropdown-item" href="https://www.facebook.com/dialog/share?app_id=248598508986158&display=popup&href=http%3A%2F%2Funbanking.ca{% url 'upvote:detail' submission.slug %}&redirect_uri=http%3A%2F%2Funbanking.ca{% url 'upvote:detail' submission.slug %}&quote={{ submission.word|upper|urlencode }} would make a great new term for 'banking'. Vote to get it to the top!">Facebook</a>
        <a class="dropdown-item" href="https://www.linkedin.com/shareArticle?mini=true&url=http%3A%2F%2Funbanking.ca{% url 'upvote:detail' submission.slug %}&title=VOTE%20NOW!&summary={{ submission.word|upper|urlencode }} would make a great new term for 'banking'. Vote to get it to the top!&source=Unbanking">Linkedin</a>
    </div>
  </div>
</div>